name: GenAI Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code_review_job:
    runs-on: ubuntu-latest
    name: ChatGPT Code Review
    steps:
      - name: GenAI Code Review
        uses: cirolini/genai-code-review@v2
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.number }}
          openai_model: "gpt-4-turbo" # or "gpt-3.5-turbo"
          openai_temperature: 0.5
          openai_max_tokens: 2048
          mode: patch # "files" to analyze file content, "patch" to summarize changes
          language: en
          custom_prompt: "Identify security vulnerabilities and suggest improvements."

