name: Code Review with GPT

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Upgrade Dependencies
        run: |
          pip install --upgrade openai httpx

      - name: Run GPT Code Review
        uses: sshnaidm/gpt-code-review-action@v2.0
        with:
          openai-key: ${{ secrets.OPENAI_API_KEY }}
          model: 'gpt-4'
          max-length: 8000
          prompt: 'Review this code for potential issues, security vulnerabilities, and best practices.'
          post-if-error: true
