name: ChatGPT Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code_review_job:
    runs-on: ubuntu-latest
    name: ChatGPT Code Review
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ChatGPT Code Review
        uses: cirolini/genai-code-review@v2
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.pull_request.number }}
          openai_model: gpt-3.5-turbo
          openai_temperature: 0.5
          openai_max_tokens: 2048
          mode: files  # Change to 'files' if errors persist
          language: en
          custom_prompt: "Analyze the code for best practices, security vulnerabilities, and improvements without executing it."
        continue-on-error: true  # Ensures workflow doesn't fail if the review action fails
