name: ChatGPT Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code_review_job:
    runs-on: ubuntu-latest
    name: ChatGPT Code Review
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: GenAI Code Review
        uses: cirolini/genai-code-review@v2
        with:
          openai_api_key: ${{ secrets.openai_api_key }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_pr_id: ${{ github.event.number }}
          openai_model: "gpt-3.5-turbo"  # Change to "gpt-4o" if needed
          openai_temperature: 0.5
          openai_max_tokens: 2048
          mode: files  # Can be "patch" to review only changes
          language: en
          custom_prompt: ""  # Optional: Add specific review instructions
